---
# Source: nifi-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi-operator-deployment
  labels:
    helm.sh/chart: nifi-operator-0.5.0-nightly
    app.kubernetes.io/name: nifi-operator
    app.kubernetes.io/instance: nifi-operator
    app.kubernetes.io/version: "0.5.0-nightly"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nifi-operator
      app.kubernetes.io/instance: nifi-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nifi-operator
        app.kubernetes.io/instance: nifi-operator
    spec:
      serviceAccountName: nifi-operator-serviceaccount
      securityContext:
        {}
      containers:
        - name: nifi-operator
          securityContext:
            {}
          image: "docker.stackable.tech/stackable/nifi-operator:0.5.0-nightly"
          imagePullPolicy: IfNotPresent
          resources:
            {}
          volumeMounts:
            - mountPath: /etc/stackable/nifi-operator/config-spec
              name: config-spec
      volumes:
        - name: config-spec
          configMap:
            name: nifi-operator-configmap
