apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
metadata:
  name: simple-nifi
spec:
  clusterConfig:
    authentication:
      - authenticationClass: simple-nifi-users
    listenerClass: external-unstable
    sensitiveProperties:
      autoGenerate: true
      keySecret: nifi-sensitive-property-key
    zookeeperConfigMapName: simple-nifi-znode
  image:
    productVersion: 1.27.0
  nodes:
    configOverrides:
      nifi.properties:
        nifi.security.user.oidc.client.id: nifi
        nifi.security.user.oidc.client.secret: R1bxHUD569vHeQdw
        nifi.security.user.oidc.discovery.url: http://172.18.0.2:32539/realms/test/.well-known/openid-configuration
        nifi.security.user.oidc.claim.identifying.user: preferred_username
    roleGroups:
      default:
        replicas: 1
