= Security

== Authentication

Every user has to authenticate themselves before using NiFI.
There are multiple options to set up the authentication of users.

=== Single user

The default setting is to only provision a single user with administrative privileges.
You need to specify the username and password of the user.

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: nifi-admin-credentials-simple
stringData:
  username: admin
  password: admin
----

[source,yaml]
----
spec:
  [...]
  config:
    authentication:
      method:
        singleUser:
          adminCredentialsSecret: nifi-admin-credentials-simple # <4>
          autoGenerate: true
----

<4> Administrator credentials for logging into the Nifi web interface. This is the name of a `Secret` resource with two fields: `username` and `password`. This `Secret` must exist but it's entries can be populated by the operator when `autoGenerate` is `true`.

Additional users can not be added.

[#authentication-ldap]
=== LDAP

NiFi supports xref:home:concepts:authentication.adoc[authentication] of users against an LDAP server. This requires setting up an xref:home:concepts:authentication.adoc#authenticationclass[AuthenticationClass] for the LDAP server.
The AuthenticationClass is then referenced in the NifiCluster resource as follows:

[source,yaml]
----
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
metadata:
  name: test-nifi
spec:
  [...]
  config:
    authentication:
      method:
        authenticationClass: ldap # <1>
----

<1> The reference to an AuthenticationClass called `ldap`

You can follow the xref:home:tutorials:authentication_with_openldap.adoc[] tutorial to learn how to set up an AuthenticationClass for an LDAP server, as well as consulting the xref:home:reference:authenticationclass.adoc[] reference.

== Authorization

NiFi supports multiple authorization methods documented https://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#multi-tenant-authorization[here].
The available authorization methods depend on the chosen authentication method.

Authorization is not fully implemented by the Stackable Operator for Apache Nifi.

=== Single user

With this authorization method, a single user has administrator capabilities.

[#authorization-ldap]
=== LDAP

The operator uses the https://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#fileusergroupprovider[`FileUserGroupProvider`] and https://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#fileaccesspolicyprovider[FileAccessPolicyProvider] to bind the LDAP user to the Nifi administrator group. This user is then able to create and modify groups and polices in the web interface. These changes local to the `Pod` running Nifi and are *not* persistent.
