== Kubernetes custom resource options
The cluster can be configured via a YAML file. This custom resource specifies the amount of replicas for each role group or role specific configuration like port definitions etc.

[source,yaml]
----
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
metadata:
  name: simple
spec:
  metricsPort: 8428
  version: "1.15.0"
  zookeeperReference:
    name: simple
    namespace: default
    chroot: /nifi
  nodes:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        config:
          httpPort: 10000
          protocolPort: 10443
          loadBalancePort: 6342
          sensitivePropertyKeySecret: nifi-sensitive-property-
        configOverrides:
          nifi.properties:
            aws.region: eu-west-1
        replicas: 2
----

== Configuration Overrides
Apache NiFi runtime configuration is stored in a file named nifi.properties. The configOverrides block allows you to add custom parameters to this file. A Full list of the available configuration options can be found in the official Apache NiFi documentation at https://nifi.apache.org/docs/nifi-docs/components/nifi-docs/html/administration-guide.html#system_properties.

Overrides consist of a key, which must match the property name in the configuration file and a value. This allows arbitrary configuration properties to be added to Spark. In the example above a property aws.region is being explicitly set to 'eu-west-1', overriding the default value.