= Usage

== Setup Prerequisites

Apache Nifi requires Apache ZooKeeper to run. This page assumes you already installed the Stackable operators for both of these products.

For details regarding the https://github.com/stackabletech/zookeeper-operator[Stackable Operator for Apache ZooKeeper] see the xref:zookeeper::index.adoc[documentation].

== Create an Apache Nifi cluster

An Apache NiFi cluster running on three nodes with SingleUser authentication is described as follows:

[source,yaml]
----
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
metadata:
  name: simple-nifi # <1>
spec:
  image:
    productVersion: 1.18.0 # <2>
    stackableVersion: 0.3.0
  zookeeperConfigMapName: simple-nifi-znode # <3>
  config:
    authentication:
      method:
        singleUser:
          adminCredentialsSecret: nifi-admin-credentials-simple # <4>
          autoGenerate: true
    sensitiveProperties:
      keySecret: nifi-sensitive-property-key
  nodes:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        config:
          log:
            rootLogLevel: INFO
        replicas: 3
----
<1> Name of the Nifi cluster.
<2> Version of the Apache Nifi container image to use. This contains the Nifi version (`1.18.0`) as well as Stackable image version (`stackable0.2.0`). For a list of available versions please check our https://repo.stackable.tech/#browse/browse:docker:v2%2Fstackable%2Fnifi%2Ftags[image registry].
<3> A reference to a `ZNode` resource. This resource must exist and cannot be reused across Nifi clusters. For details on how to create `ZNode` resources see xref:zookeeper::znodes.adoc[this page].
<4> Administrator credentials for logging into the Nifi web interface. This is the name of a `Secret` resource with two fields: `username` and `password`. This `Secret` must exist but it's entries can be populated by the operator when `autoGenerate` is `true`.

== Authentication

Every user has to authenticate themselves before using NiFI.
There are multiple options to set up the authentication of users.

=== Single user

The default setting is to only provision a single user with administrative privileges.
You need to specify the username and password of the user.
Additional users can not be added.

[#authentication-ldap]
=== LDAP

NiFi supports xref:home:concepts:authentication.adoc[authentication] of users against an LDAP server. This requires setting up an xref:home:concepts:authentication.adoc#authenticationclass[AuthenticationClass] for the LDAP server.
The AuthenticationClass is then referenced in the NifiCluster resource as follows:

[source,yaml]
----
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
metadata:
  name: test-nifi
spec:
  [...]
  config:
    authentication:
      method:
        authenticationClass: ldap # <1>
----

<1> The reference to an AuthenticationClass called `ldap`

You can follow the xref:home:tutorials:authentication_with_openldap.adoc[] tutorial to learn how to set up an AuthenticationClass for an LDAP server, as well as consulting the xref:home:reference:authenticationclass.adoc[] reference.

== Authorization

NiFi supports multiple authorization methods documented https://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#multi-tenant-authorization[here].
The available authorization methods depend on the chosen authentication method.

Authorization is not fully implemented by the Stackable Operator for Apache Nifi.

=== Single user

With this authorization method, a single user has administrator capabilities.

[#authorization-ldap]
=== LDAP

The operator uses the https://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#fileusergroupprovider[`FileUserGroupProvider`] and https://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#fileaccesspolicyprovider[FileAccessPolicyProvider] to bind the LDAP user to the Nifi administrator group. This user is then able to create and modify groups and polices in the web interface. These changes local to the `Pod` running Nifi and are *not* persistent.

== Updating NiFi

Updating (or downgrading for that matter) the deployed version of NiFi is as simple as changing the version stated in the CRD.
Continuing the example above, to change the deployed version from `1.18.0` to `1.16.3` you'd simply deploy the following CRD.

[source,yaml]
----
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
metadata:
  name: simple-nifi
spec:
  image:
    productVersion: 1.16.3 # <1>
    stackableVersion: 0.3.0 # <2>
  zookeeperConfigMapName: simple-nifi-znode
  config:
    authentication:
      method:
        singleUser:
          adminCredentialsSecret: nifi-admin-credentials-simple
    sensitiveProperties:
      keySecret: nifi-sensitive-property-key
  nodes:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        config:
          log:
            rootLogLevel: INFO
        replicas: 3
----

<1> Change the NiFi version here
<2> Change the stackable image version here

IMPORTANT: Due to a limitation in NiFi itself it is not possible to up- or downgrade a NiFi cluster in a rolling fashion.
So any change to the NiFi version you make in this CRD will result in a full cluster restart with a short downtime.
This does not affect the stackable image version, this can be changed in a rolling fashion, as long as the underlying NiFi version remains unchanged.

== Monitoring

The managed NiFi cluster is automatically configured to export Prometheus metrics. See
xref:home:operators:monitoring.adoc[] for more details.

== Configuration & Environment Overrides

The cluster definition also supports overriding configuration properties and environment variables, either per role or per role group, where the more specific override (role group) has precedence over the less specific one (role).

IMPORTANT: Do not override port numbers.
This will lead to cluster malfunction.

=== Configuration Overrides

Apache NiFi runtime configuration is stored in the files bootstrap.conf and nifi.properties.
The `configOverrides` block enables you to customize parameters in these files.
The complete list of the configuration options can be found in the  https://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#system_properties[Apache NiFi documentation].

Overrides are key, value pairs defined under a Nifi configuration file such as `bootstrap.conf` or `nifi.properties`. They must match the names values as expected by NiFi. In the example below, a property `nifi.flow.configuration.archive.enabled` is being explicitly set to 'false', overriding the default value.

The following snippet shows how to disable workflow file backups in the NifiCluster definition:

[source,yaml]
----
configOverrides:
  nifi.properties:
    nifi.flow.configuration.archive.enabled: false
----

WARNING: Please be aware that by overriding config settings in this section you have a very high risk of breaking things, because the product does not behave the way the Stackable Operator for Apache NiFi expects it to behave anymore.

=== Environment Variables

Environment variables can be (over)written by adding the `envOverrides` property.

For example per role group:

[source,yaml]
----
nodes:
  roleGroups:
    default:
      config: {}
      replicas: 1
      envOverrides:
        MY_ENV_VAR: "MY_VALUE"
----

or per role:

[source,yaml]
----
nodes:
  envOverrides:
    MY_ENV_VAR: "MY_VALUE"
  roleGroups:
    default:
      config: {}
      replicas: 1
----

=== Volume storage

By default, a Nifi cluster will create five different persistent volume claims for flow files, provenance, database, content and state folders. These PVCs will request `2Gi`. It is recommended that you configure these volume requests according to your needs.

Storage requests can be configured at role or group level, for one or more of the persistent volumes as follows:

[source,yaml]
----
nodes:
  roleGroups:
    default:
      config:
        resources:
          storage:
            flowfile_repo:
              capacity: 12Gi
            provenance_repo:
              capacity: 12Gi
            database_repo:
              capacity: 12Gi
            content_repo:
              capacity: 12Gi
            state_repo:
              capacity: 12Gi
----

In the above example, all nodes in the default group will request `12Gi` of storage the various folders.

=== Resource Requests

// The "nightly" version is needed because the "include" directive searches for
// files in the "stable" version by default.
// TODO: remove the "nightly" version after the next platform release (current: 22.09)
include::nightly@home:concepts:stackable_resource_requests.adoc[]

If no resource requests are configured explicitly, the Nifi operator uses the following defaults:

[source,yaml]
----
nodes:
  roleGroups:
    default:
      config:
        resources:
          cpu:
            min: "500m"
            max: "4"
          memory:
            limit: '2Gi'
          storage:
            flowfile_repo:
              capacity: 2Gi
            provenance_repo:
              capacity: 2Gi
            database_repo:
              capacity: 2Gi
            content_repo:
              capacity: 2Gi
            state_repo:
              capacity: 2Gi
----
