---
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: simple-nifi-admin-user
spec:
  provider:
    static:
      userCredentialsSecret:
        name: simple-nifi-admin-user-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: simple-nifi-admin-user-secret
stringData:
  # The admin user is required for a working single user NiFi deployment. The password can be changed as desired.
  admin: admin
  # Will not be read and used by NiFi (e.g. in case of reusing a Secret)
  bob: bob
---
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
metadata:
  name: simple-nifi
spec:
  image:
    productVersion: 2.7.2
  clusterConfig:
    authentication:
      - authenticationClass: simple-nifi-admin-user
    sensitiveProperties:
      keySecret: nifi-sensitive-property-key
      autoGenerate: true
  nodes:
    roleConfig:
      listenerClass: external-unstable
    roleGroups:
      default:
        replicas: 1
