---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-auth-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-authorizer
data:
  authorizers.xml: |
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <authorizers>
      <userGroupProvider>
          <identifier>file-user-group-provider</identifier>
          <class>org.apache.nifi.authorization.FileUserGroupProvider</class>
          <property name="Users File">./custom-authorizer/users.xml</property>
          <property name="Initial User Identity admin">admin</property>
          <property name="Initial User Identity other-nifis">CN=generated certificate for pod</property>
      </userGroupProvider>
      <accessPolicyProvider>
          <identifier>file-access-policy-provider</identifier>
          <class>org.apache.nifi.authorization.FileAccessPolicyProvider</class>
          <property name="User Group Provider">file-user-group-provider</property>
          <property name="Authorizations File">./custom-authorizer/authorizations.xml</property>
          <property name="Initial Admin Identity">admin</property>
          <property name="Node Identity other-nifis">CN=generated certificate for pod</property>
      </accessPolicyProvider>
      <authorizer>
          <identifier>managed-authorizer</identifier>
          <class>org.apache.nifi.authorization.StandardManagedAuthorizer</class>
          <property name="Access Policy Provider">file-access-policy-provider</property>
      </authorizer>
    </authorizers>
---
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: simple-nifi-users
spec:
  provider:
    static:
      userCredentialsSecret:
        name: simple-nifi-admin-credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: simple-nifi-admin-credentials
stringData:
  admin: adminadmin
---
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
metadata:
  name: test-nifi
spec:
  image:
    custom: null
    productVersion: "2.4.0"
    pullPolicy: IfNotPresent
  clusterConfig:
    zookeeperConfigMapName: null
    authentication:
      - authenticationClass: simple-nifi-users
    hostHeaderCheck:
      allowAll: false
    sensitiveProperties:
      keySecret: nifi-sensitive-property-key
      autoGenerate: true
    extraVolumes:
      - name: nifi-auth-config
        persistentVolumeClaim:
          claimName: nifi-auth-config
  nodes:
    roleConfig:
      listenerClass: external-unstable
    roleGroups:
      default:
        replicas: 2
    configOverrides:
      nifi.properties:
        nifi.web.https.sni.required: "false"
        nifi.web.https.sni.host.check: "true"
        nifi.authorizer.configuration.file: "/stackable/nifi/custom-authorizer/authorizers.xml"
        nifi.security.user.authorizer: "managed-authorizer"
    podOverrides:
      spec:
        initContainers:
          - name: prep-custom-authorizers
            image: oci.stackable.tech/sdp/nifi:2.4.0-stackable0.0.0-dev
            args:
              - |
                  echo Copying custom files...
                  cp /tmp/custom-authorizer/authorizers.xml /stackable/nifi/custom-authorizer/
                  echo Templating custom authorizer file...
                  config-utils template /stackable/nifi/custom-authorizer/authorizers.xml
            command:
              - /bin/bash
              - -c
              - -euo
              - pipefail
            volumeMounts:
              - name: custom-authorizer
                mountPath: /tmp/custom-authorizer
              - name: nifi-auth-config
                mountPath: /stackable/nifi/custom-authorizer
        containers:
          - name: nifi
            volumeMounts:
              - name: nifi-auth-config
                mountPath: /stackable/nifi/custom-authorizer
        volumes:
          - name: custom-authorizer
            configMap:
              name: custom-authorizer
