# Deploy a NiFi cluster, a user secret amd a ZooKeeper cluster and a respective
# ZNode `simple-nifi-znode` which will be referenced
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple-zk
spec:
  version: 3.5.8-stackable0.7.0
  servers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 3
        config: {}
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: simple-nifi-znode
spec:
  clusterRef:
    name: simple-zk
---
apiVersion: v1
kind: Secret
metadata:
  name: nifi-admin-credentials-simple
stringData:
  username: admin
  password: supersecretpassword
---
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
metadata:
  name: simple-nifi
spec:
  version: "1.15.0-stackable0.4.0"
  zookeeperConfigMapName: simple-nifi-znode
  config:
    authentication:
      method:
        singleUser:
          adminCredentialsSecret: nifi-admin-credentials-simple
          autoGenerate: true
    sensitiveProperties:
      keySecret: nifi-sensitive-property-key
      autoGenerate: true
  nodes:
    config:
      resources:
        memory:
          limit: "1"  # Option
        cpu:
          min: "2"  # Option
          max: "3" # Option
        storage:
          contentRepo:
            capacity: "10Gi"  # Option
          databaseRepo:
            capacity: "20Gi" # Option
          flowfileRepo:
            capacity: "20Gi" # Option
          provenanceRepo:
            capacity: "20Gi" # Option
          stateRepo:
            capacity: "20Gi"
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        config:
          log:
            rootLogLevel: INFO
          resources:
            memory:
              limit: "1Gi"  # Option
            cpu:
              min: "2"  # Option
              max: "3" # Option
            storage:
              contentRepo:
                capacity: "10Gi"  # Option
              databaseRepo:
                capacity: "20Gi" # Option
              flowfileRepo:
                capacity: "20Gi" # Option
              provenanceRepo:
                capacity: "20Gi" # Option
              stateRepo:
                capacity: "20Gi"
        replicas: 2
