apiVersion: nifi.stackable.tech/v1
kind: NiFiCluster
metadata:
  name: simple-nificluster
spec:
  version: "1.13.2"
  nodes:
    selectors:
      default:
        selector:
          matchLabels:
            kubernetes.io/hostname: "mdesktop"
        instances: 1
        instancesPerNode: 1
        config:
          port: 12345

