= Installation

On this page you will install the Stackable Operator for Apache NiFi and operators for its dependencies - ZooKeeper - as well as the commons and secret operator which are required by all Stackable Operators.

== Stackable Operators

There are two ways to install Stackable Operators:

1. Using xref:stackablectl::index.adoc[stackablectl]

2. Using Helm

=== stackablectl

The stackablectl command line tool is the recommended way to interact with operators and dependencies. Follow the xref:stackablectl::installation.adoc[installation steps] for your platform if you choose to work with stackablectl.

After you have installed `stackablectl` and have a Kubernetes cluster up and
running, run the following command to install all operators necessary for NiFi:

[source,bash]
----
include::example$code/getting-started.sh[tag=stackablectl-install-operators]
----

The output should contain the following lines

[source]
----
include::example$code/install-operator-output.txt[tag=stackablectl-install-operators-output]
----

TIP: Consult the xref:stackablectl::quickstart.adoc[] to learn more about how to use `stackablectl`.

=== Helm

You can also use Helm to install the operators. Add the Stackable Helm repository:

[source,bash]
----
include::example$code/getting-started.sh[tag=helm-add-repo]
----

Then install the Stackable Operators:

[source,bash]
----
include::example$code/getting-started.sh[tag=helm-install-operators]
----

Helm will deploy the operators in a Kubernetes Deployment and apply the CRDs for the Apache NiFi service (as well as the CRDs for the required operators). You are now ready to deploy Apache NiFi in Kubernetes.

== What's next

xref:first_steps.adoc[Setting up a NiFi cluster] and its dependencies.
