= Usage guide
:description: Guide to configuring the Stackable Operator for Apache NiFi with YAML manifests, covering authentication, extra volumes, and resource settings.

This section helps you to use various aspects of the Stackable operator for Apache NiFi.
For a general introduction into the operator follow the xref:getting_started/index.adoc[] guide.
Below is a general overview of some configuration aspects, have a look at the subpages for details.

The cluster is configured via a YAML manifest file.
This custom resource specifies the amount of replicas for each role group or role specific configuration like resource requests.
The following listing shows an example configuration:

[source,yaml]
----
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
metadata:
  name: simple-nifi
spec:
  image:
    productVersion: 2.7.2
  clusterConfig:
    authentication:  # <1>
      - authenticationClass: simple-nifi-admin-user
    extraVolumes:  # <2>
      - name: nifi-client-certs
        secret:
          secretName: nifi-client-certs
    sensitiveProperties:
      keySecret: nifi-sensitive-property-key
      autoGenerate: true
  nodes:
    roleConfig:
      listenerClass: external-unstable
  roleGroups:
    default:
      config:
        resources:  # <3>
          cpu:
            min: "500m"
            max: "4"
          memory:
            limit: 2Gi
        replicas: 3
----

<1> How users should xref:usage_guide/security.adoc[authenticate] themselves.
<2> xref:usage_guide/extra-volumes.adoc[Extra volumes] with files that can be referenced in custom workflows.
<3> xref:usage_guide/resource-configuration.adoc[CPU and memory configuration] can be set per role group.

Not shown are the common settings for xref:usage_guide/operations/cluster-operations.adoc[starting and stopping the cluster] and xref:usage_guide/operations/pod-placement.adoc[distributing Pods]. Additionally, you can set any NiFi setting using xref:usage_guide/overrides.adoc[overrides]. You can also configure xref:usage_guide/log-aggregation.adoc[log aggregation].
