= Resource configuration
:description: Configure NiFi storage and resource requests for optimal performance. Set PVC sizes and resource requests for CPU, memory, and persistent storage.

== Volume storage

By default, a NiFi cluster will create five different persistent volume claims for flow files, provenance, database, content and state folders.
You can find the default sizes of the PVCs in the {crd-docs}/nifi.stackable.tech/NifiCluster/v1alpha1/#spec-nodes-config-resources-storage[NifiCluster reference docs {external-link-icon}^], it is recommended that you configure these volume requests according to your needs.

Storage requests can be configured at role or group level, for one or more of the persistent volumes as follows:

[source,yaml]
----
nodes:
  roleGroups:
    default:
      config:
        resources:
          storage:
            flowfileRepo:
              capacity: 12Gi
            provenanceRepo:
              capacity: 12Gi
            databaseRepo:
              capacity: 12Gi
            contentRepo:
              capacity: 12Gi
            stateRepo:
              capacity: 12Gi
----

In the above example, all nodes in the default group will request `12Gi` of storage the various folders.

== Resource requests

include::home:concepts:stackable_resource_requests.adoc[]

A minimal HA setup consisting of 2 NiFi instances has the following https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/[resource requirements]:

* `1500m` CPU request
* `5000m` CPU limit
* `8448Mi` memory request and limit
* `18432Mi` persistent storage

You can find the default resource configuration values in the {crd-docs}/nifi.stackable.tech/NifiCluster/v1alpha1/#spec-nodes-config-resources[NifiCluster reference docs {external-link-icon}^].
