
= Resource configuration

== Volume storage

By default, a NiFi cluster will create five different persistent volume claims for flow files, provenance, database, content and state folders. These PVCs will request `2Gi`. It is recommended that you configure these volume requests according to your needs.

Storage requests can be configured at role or group level, for one or more of the persistent volumes as follows:

[source,yaml]
----
nodes:
  roleGroups:
    default:
      config:
        resources:
          storage:
            flowfileRepo:
              capacity: 12Gi
            provenanceRepo:
              capacity: 12Gi
            databaseRepo:
              capacity: 12Gi
            contentRepo:
              capacity: 12Gi
            stateRepo:
              capacity: 12Gi
----

In the above example, all nodes in the default group will request `12Gi` of storage the various folders.

== Resource Requests

include::home:concepts:stackable_resource_requests.adoc[]

A minimal HA setup consisting of 2 NiFi instances has the following https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/[resource requirements]:

* `1500m` CPU request
* `5000m` CPU limit
* `8448Mi` memory request and limit
* `18432Mi` persistent storage

Corresponding to the values above, the operator uses the following resource defaults:

[source,yaml]
----
nodes:
  roleGroups:
    default:
      config:
        resources:
          cpu:
            min: "500m"
            max: "2000m"
          memory:
            limit: '4096Mi'
          storage:
            flowfileRepo:
              capacity: 1024Mi
            provenanceRepo:
              capacity: 2048Mi
            databaseRepo:
              capacity: 1024Mi
            contentRepo:
              capacity: 4096Mi
            stateRepo:
              capacity: 1024Mi
----
