= Security
:nifi-docs-authorization: https://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#multi-tenant-authorization
:nifi-docs-fileusergroupprovider: https://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#fileusergroupprovider
:nifi-docs-fileaccesspolicyprovider: https://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#fileaccesspolicyprovider
:nifi-docs-sensitive-properties-key: https://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#nifi_sensitive_props_key

== TLS

NiFi sets up TLS encryption for the http endpoints that serve the UI.
By default, this interface is secured using certificates generated to work with the default SecretClass `tls`.

Nifi can be configured to use a different SecretClass as shown below:

[source, yaml]
----
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
spec:
  # ...
  clusterConfig:
    tls:
      serverSecretClass: non-default-secret-class # <1>
----

<1> The name of the SecretClass that will be used for certificates for the NiFi UI.

== Authentication

Every user has to authenticate themselves before using NiFI.
There are multiple options to set up the authentication of users.
All authentication related parameters are configured under `spec.clusterConfig.authentication`.

=== Single user

The `Single user` allows the creation of one admin user for NiFi.
This is a rudimentary authentication method to quickly test and log in to the canvas.
However, due to it being a single user with all rights, this is not recommended in production.

[source, yaml]
----
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: simple-nifi-users # <1>
spec:
  provider:
    static:
      userCredentialsSecret:
        name: nifi-admin-credentials # <2>
----

<1> The name of the AuthenticationClass that will be referenced in the NiFi cluster.
<2> The name of the Secret containing the admin credentials.

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: nifi-admin-credentials # <1>
stringData:
  admin: admin # <2>
  bob: bob # <3>
----

<1> The name of the Secret containing the admin user credentials.
<2> The user and password combination of the admin user. The username *must* be "admin" and cannot be changed. The NiFi pods will not start if they cannot mount the "admin" entry from the Secret. The password can be adapted.
<3> The Secret maybe used by other products of the Stackable Data Platform that allow more than one user. The Stackable Operator for Apache NiFi will ignore all users except for "admin".

[source,yaml]
----
spec:
  clusterConfig:
    authentication:
      - authenticationClass: simple-nifi-users # <1>
----

<1> The reference to an AuthenticationClass. NiFi only supports one authentication mechanism at a time.

[#authentication-ldap]
=== LDAP

NiFi supports xref:concepts:authentication.adoc[authentication] of users against an LDAP server.
This requires setting up an AuthenticationClass for the LDAP server.
The AuthenticationClass is then referenced in the NifiCluster resource as follows:

[source,yaml]
----
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
metadata:
  name: test-nifi
spec:
  clusterConfig:
    authentication:
      - authenticationClass: ldap # <1>
----

<1> The reference to an AuthenticationClass called `ldap`

You can follow the xref:tutorials:authentication_with_openldap.adoc[] tutorial to learn how to set up an AuthenticationClass for an LDAP server, as well as consulting the {crd-docs}/authentication.stackable.tech/authenticationclass/v1alpha1/[AuthenticationClass reference {external-link-icon}^].

[#authentication-oidc]
=== OIDC

NiFi supports xref:concepts:authentication.adoc[authentication] of users against an OIDC provider.
This requires setting up an AuthenticationClass for the OIDC provider and specifying a Secret containing OIDC client and OIDC client Secret as part of the NiFi configuration.
The AuthenticationClass and the OIDC client credentials Secret are then referenced in the NifiCluster resource:

[source,yaml]
----
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
metadata:
  name: test-nifi
spec:
  clusterConfig:
    authentication:
      - authenticationClass: oidc # <1>
        oidc:
          clientCredentialsSecret: nifi-oidc-client # <2>
----

<1> The reference to an AuthenticationClass called `oidc`
<2> The reference to an existing Secret called `nifi-oidc-client`

[source,yaml]
----
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: oidc
spec:
  provider:
    oidc:
      hostname: keycloak.example.com
      rootPath: /realms/test/ # <1>
      principalClaim: preferred_username
      scopes:
        - openid
        - email
        - profile
      port: 8080
      tls: null
  [...]
----

<1> A trailing slash in `rootPath` is necessary.

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: nifi-oidc-client
stringData:
  clientId: <client-id>
  clientSecret: <client-secret>
----

[#authorization]
== Authorization

NiFi supports {nifi-docs-authorization}[multiple authorization methods], the available authorization methods depend on the chosen authentication method.

Authorization is not fully implemented by the Stackable Operator for Apache NiFi.

[#authorization-single-user]
=== Single user

With this authorization method, a single user has administrator capabilities.

[#authorization-ldap]
=== LDAP

The operator uses the {nifi-docs-fileusergroupprovider}[`FileUserGroupProvider`] and {nifi-docs-fileaccesspolicyprovider}[FileAccessPolicyProvider] to bind the LDAP user to the NiFi administrator group.
This user is then able to create and modify groups and policies in the web interface.
These changes local to the Pod running NiFi and are *not* persistent.

[#authorization-oidc]
=== OIDC

With this authorization method, all authenticated users have administrator capabilities. 

An admin user with an auto-generated password is created that can access the NiFi API.
The password for this user is stored in a Kubernetes Secret called `<nifi-name>-oidc-admin-password`.

[#encrypting-sensitive-properties]
== Encrypting sensitive properties on disk

Some flows require storing a sensitive property like a password or access token, which is then stored on disk.
NiFi {nifi-docs-sensitive-properties-key}[encrypts these properties] in flow files.

The sensitive property encryption is configured using the properties `keySecret`, `autoGenerate` and `algorithm` in the {crd-docs}/nifi.stackable.tech/nificluster/v1alpha1/#spec-clusterConfig-sensitiveProperties[`spec.clusterConfig.sensitiveProperties` {external-link-icon}^] configuration section of the NifiCluster resource.

The `keySecret` configures the name of the Secret object that holds the encryption key; it is required to specify a Secret name.
The Secret needs to contain the key as a value to the `nifiSensitivePropsKey` key.
You can either specify a key yourself - in which case the key needs to be at least 12 characters long - or just specify the name of the Secret and set `autoGenerate` to `true` (the default is false).
If `autoGenerate` is false and no Secret with the given name in `keySecret` is found, the operator will raise an error.

The `algorithm` property configures the encryption algorithm used to encrypt the sensitive properties.
Consult the {crd-docs}/nifi.stackable.tech/nificluster/v1alpha1/#spec-clusterConfig-sensitiveProperties-algorithm[reference documentation {external-link-icon}^] for a list of supported algorithms.

=== Autogenerated key example

Let the operator generate a Secret with the name `nifi-sensitive-property-key`:

[source,yaml]
----
sensitiveProperties:
  keySecret: nifi-sensitive-property-key
  autoGenerate: true
----

=== Custom key and encryption algorithm example

Create the Secret yourself:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: nifi-sensitive-properties-key
stringData:
  nifiSensitivePropsKey: my-encryption-key
----

Configure the Secret and a different encryption algrithm:

[source,yaml]
----
sensitiveProperties:
  keySecret: nifi-sensitive-property-key
  algorithm: nifiArgon2AesGcm256
----
