name: Docker

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - shell: bash
        env:
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: make docker
