name: Publish-Nightly-Packages

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  debian10:
    runs-on: debian10
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ~/.cargo/bin/cargo +nightly build --verbose --release
      - name: Build apt package
        run: ~/.cargo/bin/cargo deb --manifest-path server/Cargo.toml --no-build
      - name: Publish apt package
        run: >-
          /usr/bin/curl
          -vvvv
          --fail
          -u 'github:${{ secrets.NEXUS_PASSWORD }}'
          -H "Content-Type: multipart/form-data"
          --data-binary "@./$(find target/debian/ -name *.deb)"
          "https://repo.stackable.tech/repository/deb-nightly/"

  centos:
    runs-on: centos${{ matrix.node }}
    strategy:
      matrix:
        node: [ 7, 8 ]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ~/.cargo/bin/cargo +nightly build --verbose --release
      - name: Build RPM package
        run: server/packaging/buildrpm.sh stackable-nifi-operator-server
      - name: Publish RPM package
        run: >-
          /usr/bin/curl
          -vvvv
          --fail
          -u 'github:${{ secrets.NEXUS_PASSWORD }}'
          --upload-file "./$(find  target/rpm/RPMS/x86_64/ -name *.rpm)"
          "https://repo.stackable.tech/repository/rpm-nightly/el${{ matrix.node }}/"